<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Partners_fa fa-angle-up</name>
   <tag></tag>
   <elementGuidId>3bd41f91-ad4f-4a45-9d76-7857de95dc80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-angle-up</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-9406']/a[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-angle-up</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky-wrapper&quot;)/header[@class=&quot;saspot-header  saspot-sticky&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-xl-7 col-lg-8 col-md-6 col-2&quot;]/div[@class=&quot;header-right mean-container&quot;]/div[@class=&quot;mean-bar&quot;]/nav[@class=&quot;mean-nav&quot;]/ul[@id=&quot;menu-main-menu&quot;]/li[@id=&quot;menu-item-9406&quot;]/a[@class=&quot;mean-expand mean-clicked&quot;]/i[@class=&quot;fa fa-angle-up&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-9406']/a[2]/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a[2]/i</value>
   </webElementXpaths>
</WebElementEntity>
